package: glossar
version: '0.3'
author: Oliver Kreischer
supportpage: https://github.com/olien/glossar/issues
compile: 0

page:
  title: 'translate:glossar'
  perm: glossar[]
  pjax: true
  icon: rex-icon fa-font
  subpages:
        main: { title: 'translate:glossar' }

requires:
  redaxo: '>=5.1.0'
