package: glossar
version: '0.1'
author: Oliver Kreischer
supportpage: https://github.com/olien/glossar/issues
compile: 0

page:
  title: 'translate:glossar'
  perm: glossar[general]
  pjax: false
  icon: rex-icon fa-google

requires:
  redaxo: '>=5.1.0'
